### ISSUE TITLE
Update README to indicate we're published

### ISSUE THREAD

**Issue by nhooyr** [terrastruct/d2-vscode#10]

**Comment by alixander** [comment]
r we not

**Comment by nhooyr** [comment]
lol if we are we ought to update the README to indicate that.

I don't remember publishing at least.

oh yea looks like I did: https://marketplace.visualstudio.com/items?itemName=terrastruct.d2

Ok so this issue is updating the README then.

**Comment by alixander** [comment]
bernard did
