### ISSUE TITLE
syntax highlighting bug with unclosed bracket in code

### ISSUE THREAD

**Issue by gavin-ts** [terrastruct/d2-vscode#108]
### closed bracket
![Screen Shot 2023-06-19 at 11 43 20 AM](https://github.com/terrastruct/d2-vscode/assets/85081687/4578dcdf-1459-49af-a86c-163504a09139)

### unclosed bracket
![Screen Shot 2023-06-19 at 11 43 10 AM](https://github.com/terrastruct/d2-vscode/assets/85081687/9dc8bc8c-9be7-4791-8aeb-6228b51d107a)

### md is ok, but not js
![Screen Shot 2023-06-20 at 10 47 25 AM](https://github.com/terrastruct/d2-vscode/assets/85081687/7fa3f8e4-348f-42bb-90ac-33cc1209b076)

```d2
Code: |js function todo() { | {
  style.stroke-width: 0
}
Text
```

**Comment by BarryNolte** [comment]
@gavin-ts I'm getting 404 errors trying to view the screen shots.

**Comment by gavin-ts** [comment]
> @gavin-ts I'm getting 404 errors trying to view the screen shots.

updated

**Comment by BarryNolte** [comment]
Turns out that "| {" is "fairly valid" javascript, so the syntax highlighting just keeps going thinking it's javascript instead of terminating the block of code.
