### ISSUE TITLE
vsc preview error

### ISSUE THREAD

**Issue by jacealan** [terrastruct/d2-vscode#109]
<img width="559" alt="image" src="https://github.com/terrastruct/d2-vscode/assets/33442365/bd9c6639-19de-4e42-aa52-d85fd9aef2ce">

on vsc(Mac Venture 13.4.1), the preview of *.d2 makes error now.
Until a few days ago, it worked well.

but on terminal, d2 is working well.
```
//flow.d2
x -> y
```

```
$ d2 flow.d2
success: successfully compiled flow.d2 to flow.svg in 55.019709ms
```

**Comment by alixander** [comment]
@jacealan the error message is right. the environment that you're running `d2` in terminal likely just doesn't have the env var set. come to think of it though, it is a fault on our side that we treat that as a fatal error. i've made an issue to address here: https://github.com/terrastruct/d2/issues/1436

**Comment by BarryNolte** [comment]
I couldn't reproduce this (not for lack of trying), but I totally believe it's happening.  @alixander you beat me to this solution.
