### ISSUE TITLE
do not force color theme on extension activation.

### ISSUE THREAD

**Issue by davidlaym** [terrastruct/d2-vscode#110]
Color theme for the whole visual studio code experience is a very sensitive thing to be changing without express consent from the user. Please make the themes available, but do not activate any theme without interaction.

**Comment by BarryNolte** [comment]
I rest my case... #52

**Comment by BarryNolte** [comment]
This may be a "feature" of vscode.  @davidlaym, does this only happen while developing an extension in vscode?

Possible explanation:
https://github.com/microsoft/vscode/issues/88169

**Comment by davidlaym** [comment]
No, just by normal usage loading a project (multi-root workspace). It happened on the first install of the extension, it changed my color theme. Second time it happened when opening vscode again another day (I think the extension had an update) and it just changed my theme with the d2 dark one. I have opened vscode after a reboot for example and my theme has been respected. 
I do not develop extensions, just nodejs apis and react-native apps.

**Comment by BarryNolte** [comment]
This sounds/smells like a conflict between extensions.  Can you run, "Help: Start Extension Bisect", to automatically run through turning extensions on and off to determine which one it might be?

**Comment by davidlaym** [comment]
It hasn't come up again in these 2 weeks, so I think it was some odd behavior that came up a couple of times after install. I have updated vscode and all, so I think is no-repro for me now. Going to close the issue and if I find something else, will come back and expand. 

Thanks for your help!

**Comment by clement-lefevre** [comment]
Is the issue at hand here supposed to have been fixed? I installed the extension for the first time today, and got my theme changed out of the blue when all I was expecting was some features alongside D2.
