### ISSUE TITLE
Horizontal scrolling issue in Preview mode

### ISSUE THREAD

**Issue by Wodooman** [terrastruct/d2-vscode#128]
![Screenshot 2023-12-05 at 11 54 56](https://github.com/terrastruct/d2-vscode/assets/20907675/c6bb1efb-712a-4c8c-b32f-d74572820247)
Environment: Visual Studio Code 1.84.2, D2 VS Code Extension v0.8.8, MacOS 14.0
Steps to reproduce:
- open a d2 file with a horizontally long diagram
- zoom in (with both "+" or Ctrl+Scroll)

Expected result: horizontal scrolling will also "zoom" - so it's possible to scroll to the end of a diagram

Actual result: horizontal scrolling stays as before and it's not possible to scroll to the very end of a diagram

Workaround: after resizing windows (by moving the vertical splitter) - scrolling will be fixed ("zoomed" to scale that allows to scroll to the very end)

**Comment by BarryNolte** [comment]
This bug was fixed in the #117 branch.  Hopefully we can get that PR accepted soon.

**Comment by djukxe** [comment]
Can we reopen this issue as no fix has been implemented yet?

**Comment by dudeofawesome** [comment]
I've also found that zooming in step further than you want and then zooming out 1 step will work around this issue.
