### ISSUE TITLE
Render markdown preview with d2 diagrams in code blocks with language `d2`

### ISSUE THREAD

**Issue by kdheepak** [terrastruct/d2-vscode#14]
Thanks for making `d2` (and making it open source)! I've been playing around with it and it is great! I also like that there's a vscode and vim extension officially maintained! That's great that you are putting all this effort into making the ecosystem better.

I wanted to check if you were interested in adding a feature that would allow for markdown previews with `d2` code blocks to be rendered in the markdown preview. Mermaid, plantuml, graphviz all have third party extensions that do this that you can find on the marketplace. I think it'd be great if this feature was officially supported. 

I see that there's already a PR for split screen https://github.com/terrastruct/d2-vscode/pull/11 which is a great start, but it doesn't quite solve the use case I'm thinking about. 
I can imagine most users writing documentation in markdown will likely use a live markdown preview to make sure their document renders properly, and it would be nice to have `d2` diagrams rendered in this preview.

I made a prototype extension for this, this is what it looks like in practice:

<img width="1512" alt="Screenshot 2022-12-21 at 9 17 30 PM" src="https://user-images.githubusercontent.com/1813121/209040657-d4f7b5d4-6c70-4de1-81d3-7478e1b3b58a.png">

I'm happy to maintain this extension if you feel this feature is out of scope for the official extension. Here's the marketplace and github link to the extension for reference if you want to take a look at the extension or the code:

- https://marketplace.visualstudio.com/items?itemName=kdheepak.d2-markdown-preview
- https://github.com/kdheepak/d2-markdown-preview

**Comment by alexclaydon** [comment]
This is a great idea.  I've been using D2's Obsidian plugin this week, which provides rendering of inline code blocks, and have quickly come to find it indispensable.  Would love to have similar functionality for the official VS Code plugin.  In the meantime, thanks @kdheepak for generously contributing the above - works perfectly for me!

**Comment by BarryNolte** [comment]
PR #16 added this as a feature, awaiting review to be merged into main.  Only tested with the built-in markdown functionality.

**Comment by shah** [comment]
Great idea @alexclaydon and @BarryNolte; in addition to this support, I suggest #26 to help generalize it and use the `.d2.png` and `.d2.svg` in any linkable file.

**Comment by BarryNolte** [comment]
This specific issue should be closed.  PR #21 took care of the initial issue and #26 captures the new feature request.
