### ISSUE TITLE
regex parsing error with urls

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-vscode#31]
https://d2lang.com/tour/interactive#links

the `:` probably messing it up

<img width="317" alt="Screen Shot 2023-01-20 at 12 28 25 AM" src="https://user-images.githubusercontent.com/3120367/213650435-98474ec4-9e51-4dae-ac8e-c72bee9cc099.png">

**Comment by BarryNolte** [comment]
I'm not sure I'm seeing what you're seeing.  What's the error?

Although I could make a case for the single quote getting colored incorrectly.

**Comment by alixander** [comment]
ah i thought it was the colon, but it's the single quote causing problems. the original issue was i was seeing the ending bracket be error coded red. but it happens whenever i have a single quote. 

<img width="117" alt="Screen Shot 2023-01-20 at 11 12 21 AM" src="https://user-images.githubusercontent.com/3120367/213785799-7d01709b-bd54-47d9-875b-29637d36d1c1.png">
