### ISSUE TITLE
Show 2D Preview gives an error in VSCode

### ISSUE THREAD

**Issue by ledzepff** [terrastruct/d2-vscode#33]
Hi. 

OS: Windows 11
VSCode: 1.74.3

I've tried to start with the d2 VSCode plugin and immediately faced an error. I wanted to try d2 by using the hello world example, when I select "Show D2 Preview" I get the following error:

A system error occurred (ENOENT: no such file or directory, open 'C:\Users\<user>\AppData\Local\Temp\2023023-3048-g37xzx.86uwmout.d2.temp'

There is no such file in this directory. I've uninstalled and installed the plug-in, but this didn't help.

![image](https://user-images.githubusercontent.com/23192113/213970379-5e786108-5321-461b-b0e0-03d61672b076.png)

Any idea how to solve this?

**Comment by BarryNolte** [comment]
I'll take a look in the morning.

**Comment by BarryNolte** [comment]
Do you have the D2 cli installed and on your path?

**Comment by syjeon121** [comment]
@BarryNolte 
`(ENOENT: no such file or directory, open '/var/folders/5z/_msym8cn7fx8n1tlk28nrh440000gn/T/2023023-36038-ko2a7a.adqybout.d2.temp').`

i also found similar error, thank u

os: mac
vscode: 1.74.3

**Comment by opplol** [comment]
i also found similar error in windows.
and i resolve this with install precompiled file.
https://github.com/terrastruct/d2/releases/download/v0.1.6/d2-v0.1.6-windows-amd64.msi

**Comment by BarryNolte** [comment]
OK, after some investigation, it appears that we have poor behavior if the D2 executable can't be found.  

Immediate solution is to install the D2 command line tools and make sure it's on you path.  This is required for the extension to work.  Go to https://d2lang.com 

I've got a PR ready to address this by providing a much better error message and directions on where to go to install the CLI tools.

**Comment by ledzepff** [comment]
Hi,

I apologize for the late response. 

I've cloned d2, built it, and added d2 to the path. After that, it vscode plugin starts working.

**Comment by syjeon121** [comment]
hi i also installed d2 at https://d2lang.com/ with`brew`
after that, plugin works well. thanks

**Comment by iAdanos** [comment]
With a version installed from VSCode Marketplace (0.6.0) problem still persists on Linux (Ubuntu 20.04, Ubuntu 22.04). It seems that extension version didn't update [there](https://marketplace.visualstudio.com/items?itemName=terrastruct.d2).

After [building](https://github.com/terrastruct/d2-vscode#offline-distribution) 0.6.1 from git, new problem appeared:

```
D2 executable not found.
Make sure the D2 executable is installed and on system PATH.
https://d2lang.com/tour/install
spawnSync d2 ENOENT
```

If D2 CLI is required to be installed on the system for the extension to work - please update Readme with a note about this.

Also, in progress of building `vsix` from code, on Linux (in docker 'node:latest' official image) I encountered an error
```
# npm run pkg

> d2@0.6.1 pkg
> vsce package --out d2.vsix

 INFO  Detected presence of yarn.lock. Using 'yarn' instead of 'npm' (to override this pass '--no-yarn' on the command line).
Executing prepublish script 'yarn run vscode:prepublish'...
yarn run v1.22.19
warning d2@0.6.1: The engine "vscode" appears to be invalid.
$ yarn run package
warning d2@0.6.1: The engine "vscode" appears to be invalid.
$ webpack --mode production --devtool hidden-source-map
    [webpack-cli] Compiler starting...
    [webpack-cli] Compiler is using config: '/app/webpack.config.js'
    [webpack-cli] Compiler finished
asset extension.js 48.3 KiB [compared for emit] [minimized] (name: main) 1 related asset
cacheable modules 126 KiB
  modules by path ./node_modules/ 106 KiB 19 modules
  modules by path ./src/*.ts 20.2 KiB
    ./src/extension.ts 6.51 KiB [built] [code generated]
    ./src/docToPreviewGenerator.ts 5.2 KiB [built] [code generated]
    + 6 modules
external "vscode" 42 bytes [built] [code generated]
external "child_process" 42 bytes [built] [code generated]
external "fs" 42 bytes [built] [code generated]
external "path" 42 bytes [built] [code generated]
external "constants" 42 bytes [built] [code generated]
external "os" 42 bytes [built] [code generated]
external "assert" 42 bytes [built] [code generated]
external "util" 42 bytes [built] [code generated]
external "events" 42 bytes [built] [code generated]
webpack 5.75.0 compiled successfully in 1855 ms
Done in 2.40s.
 INFO  Detected presence of yarn.lock. Using 'yarn' instead of 'npm' (to override this pass '--no-yarn' on the command line).
 ERROR  Command failed: yarn list --prod --json
{"type":"error","data":"Couldn't find package \"fsevents@~2.3.2\" required by \"chokidar@3.5.3\" on the \"npm\" registry."}

```

The solution is similar to https://stackoverflow.com/a/66385743:

Open package-lock.json and change
```
  "node_modules/fsevents": {
      "version": "2.3.2",
      ...
      "os": [
        "darwin"
      ],
      ...
    },
```

to 

```
  "node_modules/fsevents": {
      "version": "2.3.2",
      ...
      "os": [
        "linux"
      ],
      ...
    },
```

After rolling back to stock 0.6.0 version and [installing CLI](https://d2lang.com/tour/install#install-script), the problem disappeared and everything works fine.

**Comment by alixander** [comment]
yeah sorry, forgot to update it on marketplace, it's now updated. i just tried running and didn't get that error. i've also added a line to the README about needing D2 installed. Thanks @iAdanos !

<img width="835" alt="Screen Shot 2023-01-31 at 11 28 10 PM" src="https://user-images.githubusercontent.com/3120367/215978560-294b3298-7f3c-4cf1-a667-fa9fa07d9a62.png">
