### ISSUE TITLE
create d2 compile task

### ISSUE THREAD

**Issue by gavin-ts** [terrastruct/d2-vscode#36]
1. create a vs code task to run d2.
2. create a problem matcher to parse errors or successful compile.
3. preview should be updated to render using this task
4. display errors from matched compile error

### example success output to match
```sh
% d2 in.d2 
success: successfully compiled in.d2 to in.svg
```

### example error output to match
```sh
% d2 in.d2 
err: failed to compile: 5:1: invalid text beginning unquoted key
err: 7:1: unexpected map termination character } in file map
err: 8:1: block string must be terminated with |
```

See: https://code.visualstudio.com/docs/editor/tasks and https://code.visualstudio.com/api/extension-guides/task-provider

**Comment by BarryNolte** [comment]
I've been poking at this as time permits, I should have a full report and a list of problems/concerns this weekend.  The big issue I'm having is that the file we compile is not the same name as the document (this is to handle the 'untitled' document and update when changed cases), which makes the 'jump to source' not work.  I think I have a solution, but requires some plumbing work.

**Comment by BarryNolte** [comment]
All aboard the struggle bus... but I got it.  I found the spot in the VSCode that is the least documented.

@gavin-ts Take a look at my branch [https://github.com/BarryNolte/d2-vscode/tree/CustomTaskBasedExecution](TaskBranchl).  It should be fully functional, I'm going to test it a bit more before I create a PR.

**Comment by gavin-ts** [comment]
> @gavin-ts Take a look at my branch [https://github.com/BarryNolte/d2-vscode/tree/CustomTaskBasedExecution](TaskBranchl). It should be fully functional, I'm going to test it a bit more before I create a PR.

just looking at the code it seems pretty good. I remembered an enhancement I was thinking of to skip the temp files that might make things a little simpler, so I added an issue for it here #39. will try it out
