### ISSUE TITLE
customize key bindings

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-vscode#41]
https://twitter.com/golinvauxb/status/1620393448640745479

>  hello... The D2 extension for vscode steals the CTRL+SHIFT+D shortcut from vscode (that used to open the debug side panel). 
> Is it possible to customize this keybind? I do not know how to modify such keybindings (that appear in the "Default" list). TIA!

**Comment by BarryNolte** [comment]
Is this irony or Freudian? I used to work on debuggers...

This can be changed to whatever we want, this is the default I picked.  On top of that, through 'Preferences: Open Keyboard....'

**Comment by gavin-ts** [comment]
<img width="967" alt="Screen Shot 2023-01-31 at 11 26 23 AM" src="https://user-images.githubusercontent.com/85081687/215862402-9402757d-e90a-4e27-a41f-38b5d33990e3.png">
I think we just need to add a when condition so it is context dependent and only applies on a d2 file? (if specifying that is possible)

**Comment by gavin-ts** [comment]
<img width="848" alt="Screen Shot 2023-01-31 at 11 32 45 AM" src="https://user-images.githubusercontent.com/85081687/215863663-84e4270a-9bd7-4c14-bc89-88f80b152610.png">

maybe we can define a regex match similar to what gitlens does here

**Comment by bgolinvaux** [comment]
Hello. I am sorry, I am feeling really dumb, but the shortcut appeared in the Default (read-only) keyboard shortcuts and, not really knowing how extensions register their shortcuts, I mistakenly thought that it could not be changed.

Apologies for the silly request.

**Comment by BarryNolte** [comment]
Oh, there was a bug here :)  The shortcut was active in any context, thus blocking the debug panel activation.  I changed it to only be active when a d2 document is active, which works since running the debugger on a d2 document doesn't make any sense.  But, of course, you can change it to any key combination you want.
