### ISSUE TITLE
Terminal opens when using "Format Document"

### ISSUE THREAD

**Issue by terrybrash** [terrastruct/d2-vscode#43]
Extension version: 0.6.1

Expectation:
The terminal shouldn't open when formatting a D2 document.

Steps to reproduce:
1. Open a d2 document.
2. Run `editor.action.formatDocument`, hotkey <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>F</kbd>
3. Terminal opens and displays a message "Document hello.d2 formatted."
4. Close the terminal, format again, terminal opens again.

**Comment by BarryNolte** [comment]
This behavior will change in the 0.8.0 build. No more surprise outputChannels.

**Comment by Bjorn-Eric-Abr** [comment]
Hi! Love the plugin (and D2). I got a similar issue, the D2-output open with the latest message being `[11:40:10] - Preview for graf.d2 updated.`. Will 0.8.0 fix this as well? Thanks

**Comment by BarryNolte** [comment]
Same issue, I got overzealous with the output channel and popped it out front whenever I wrote to it.

**Comment by Bjorn-Eric-Abr** [comment]
Hahaha just go for it!

**Comment by BarryNolte** [comment]
The latest build fixes this.  I'm not sure when it will be pushed to the extension marketplace.
