### ISSUE TITLE
Add support for ctrl+scroll in preview mode 

### ISSUE THREAD

**Issue by DeflateAwning** [terrastruct/d2-vscode#50]
An easy way to zoom in on a part of the diagram is paramount. I propose Browser-style `ctrl+scroll wheel` as the standard zoom.

**Comment by BarryNolte** [comment]
There seems to be some noise from the VSCode team on how `ctrl+scroll wheel` is supposed to behave because they can't differentiate between the scroll wheel and trackpad gestures.  I'll see if I can figure out how to 'do the right thing' in our webview.

**Comment by DeflateAwning** [comment]
Ctrl+Scroll should zoom in on the section where the mouse is

**Comment by BarryNolte** [comment]
Yup, working on it right now.  Change in d2 broke my zooming in d2-vscode
