### ISSUE TITLE
error makes preview look frozen

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-vscode#54]
I compiled with dagre, using a keyword it does not support, which returns an error from the CLI.

<img width="964" alt="Screen Shot 2023-03-01 at 8 31 37 PM" src="https://user-images.githubusercontent.com/3120367/222331755-591ffed9-810e-4948-b9a5-ee3247273dba.png">

However, instead of seeing this error, the preview just keeps Loading

https://user-images.githubusercontent.com/3120367/222331722-11e46ac7-2eb0-495d-85a0-34032f91981a.mp4

(this is probably because the error handling currently only works on a specific type of error that returns line numbers?)

```
input: |d2
  hello -> world
|

input -> compiler.parse

compiler: {
  parse -> AST
  AST: Abstract Syntax Tree {
    shape: oval
  style.fill: honeydew
  }

  AST -> IR: compile
  IR: Intermediate Representation (IR)
  IR -> graph: compile IR into graph
  graph: Graph\n(shapes & connections) {
    shape: oval
    style.fill: honeydew
  }
}

compiler.graph -> Set Dimensions
Set Dimensions -> Use ruler to measure all texts -> measured graph
Set Dimensions -> Use given, premeasured dimensions -> measured graph

measured graph: {
  shape: oval
  style.fill: honeydew
}

measured graph -> layout engine -> positioned graph

positioned graph: {
  shape: oval
  style.fill: honeydew
}

positioned graph -> exporter -> diagram

diagram: finalized diagram (styled) {
  shape: oval
  style.fill: honeydew
}

diagram -> render SVG

render SVG -> use sketch post processor: optional

use sketch post processor -> SVG bytes

SVG bytes: {
  shape: oval
  style.fill: honeydew
}

SVG bytes -> screenshot for PNG: optional

Legend: {
  top: 0
  left: 0
  blue: "" {
    width: 20
    height: 20
    style.stroke: black
  }
  blue-explanation: Actions {
    shape: text
  }

  green: "" {
    width: 20
    height: 20
    style.fill: honeydew
    style.stroke: black
  }
  green-explanation: Intermediate artifacts {
    shape: text
  }
}
```

(works fine i remove the top and left. awesome improvement since I last used this plugin @BarryNolte @gavin-ts . i'm switching to vscode to edit D2)

<img width="2269" alt="Screen Shot 2023-03-01 at 8 33 47 PM" src="https://user-images.githubusercontent.com/3120367/222331992-59674d92-46a6-4222-8982-e1b5560ca07a.png">

**Comment by BarryNolte** [comment]
This could be handled better, but bug https://github.com/terrastruct/d2/issues/838#issue-1590059132 really needs to be fixed for a complete fix.

**Comment by alixander** [comment]
hmm i see. yeah whatever can include line numbers, should. and this should.

however there can always be errors without line numbers. a panic or error anywhere past the compiler, like a panic in the layout engine or something. so i think the plugin still should account for line-numberless errors

**Comment by BarryNolte** [comment]
This should be fixed now.
