### ISSUE TITLE
links in diagrams not working

### ISSUE THREAD

**Issue by johannes-z** [terrastruct/d2-vscode#68]
As the title says, if you have a diagram with a `link` to e.g. another local `.md` file and click it, nothing happens. For example (remove backslash):

```md
[getting-started](./getting-started.md)

```d2
getting-started {
  link: ./getting-started.md
}
\```
```

normal link works, link in diagram doesn't. I checked with the developer console what the differences are. While there are other attribute son the `a` element, they don't change the behavior. I tried copying the attributes from the working link to the diagram link, but that didn't help either. I guess it has to do with it being wrapped by an `<svg>`.

**Comment by BarryNolte** [comment]
This is a vscode security issue.  I can work around it.

**Comment by alixander** [comment]
can you say more about the solution you're thinking @BarryNolte ?
