### ISSUE TITLE
call autoformat on save

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-vscode#7]

**Comment by BarryNolte** [comment]
I think this would require a formatter for the d2 language first, which is another extensibility point for an extension.

**Comment by alixander** [comment]
@BarryNolte it exists. `d2 fmt` on the command line.

you can test it out by compiling `x -----> y` on https://play.d2lang.com

**Comment by BarryNolte** [comment]
Well, I know how to do that :).  I can add that as another PR after the first one is accepted.

**Comment by BarryNolte** [comment]
This has been fixed.
